# Etape 3 Ajoutez de nouvelles variables à votre modèle pour améliorer les performances

In [1]:
#Importing data
import pandas as pd
data = pd.read_pickle("data/trees_clean.p")
data.head(5)

,SOUS_CATEGORIE,CODE_PARENT,ADR_SECTEUR,GENRE_BOTA,ESPECE,STADEDEDEVELOPPEMENT,ANNEEDEPLANTATION,COLLECTIVITE,LONGITUDE,LATITUDE
13,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709930,45.201111
14,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709895,45.201185
15,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709864,45.201254
16,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709828,45.201321
17,ESP151,ESP36926,1,Platanus,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709681,45.201682

In [4]:
data['GENRE_BOTA_ESPECE'] = data['GENRE_BOTA']+' '+ data['ESPECE']

In [5]:
data

,SOUS_CATEGORIE,CODE_PARENT,ADR_SECTEUR,GENRE_BOTA,ESPECE,STADEDEDEVELOPPEMENT,ANNEEDEPLANTATION,COLLECTIVITE,LONGITUDE,LATITUDE,GENRE_BOTA_ESPECE
13,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709930,45.201111,NaN
14,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709895,45.201185,NaN
15,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709864,45.201254,NaN
16,ESP151,ESP36926,1,NaN,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709828,45.201321,NaN
17,ESP151,ESP36926,1,Platanus,NaN,NaN,2017.0,Grenoble Alpes Métropole,5.709681,45.201682,NaN
...,...,...,...,...,...,...,...,...,...,...,...
31238,ESP151,ESP1277,1,Fraxinus,oxycarpa,Arbre adulte,2001.0,Grenoble Alpes Métropole,5.711717,45.193945,Fraxinus oxycarpa
31239,ESP151,ESP1277,1,Fraxinus,oxycarpa,Arbre adulte,2001.0,Grenoble Alpes Métropole,5.711590,45.193915,Fraxinus oxycarpa
31240,ESP151,ESP1277,1,Fraxinus,oxycarpa,Arbre adulte,2001.0,Grenoble Alpes Métropole,5.711487,45.194140,Fraxinus oxycarpa
31241,ESP151,ESP1277,1,Fraxinus,oxycarpa,Arbre adulte,2001.0,Grenoble Alpes Métropole,5.711786,45.193965,Fraxinus oxycarpa
31242,ESP151,ESP1277,1,Fraxinus,oxycarpa,Arbre adulte,2001.0,Grenoble Alpes Métropole,5.711336,45.194467,Fraxinus oxycarpa